version: "2"
services:
  ciexpress:
    container_name: ciexpress
    restart: always
    image: sunilmore690/ciexpress
    ports:
      - "80:3000"
    links:
      - mongo  
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data:/data/db
    ports:
      - "27017:27017"